version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: etudiants
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
