name: CI/CD PHP Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/php-student-app:latest

      - name: Deploy to local Mac via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.MAC_HOST }}       # IP ou nom DNS de ton Mac
          username: ${{ secrets.MAC_USER }}   # utilisateur macOS
          key: ${{ secrets.SSH_PRIVATE_KEY }} # clé privée SSH (sans passphrase)
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/php-student-app:latest
            docker stop php-student-app || true
            docker rm php-student-app || true
            docker run -d --name php-student-app -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/php-student-app:latest
